version: "3"

services:
  srv:
    container_name: lisn_srv
    build: .
    ports:
      - 80:80
    depends_on:
      - db

  db:
    container_name: lisn_db
    image: postgres:13-alpine
    env_file:
      - db.env
    ports:
      - 5432:5432
